name: data-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google service account file
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -n "$GOOGLE_SERVICE_ACCOUNT_JSON" ]; then
            echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > service-account.json
          else
            echo 'GOOGLE_SERVICE_ACCOUNT_JSON secret not set; skipping file creation.'
          fi

      - name: Run PEAllm data pipeline
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          HF_DATASET_REPO_ID: ${{ secrets.HF_DATASET_REPO_ID }}
          GOOGLE_SERVICE_ACCOUNT_FILE: ${{ github.workspace }}/service-account.json
          GOOGLE_DRIVE_RAW_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_RAW_FOLDER_ID }}
          GOOGLE_DRIVE_PROCESSED_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_PROCESSED_FOLDER_ID }}
          GOOGLE_DRIVE_PDPA_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_PDPA_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          HF_TRAINING_TRIGGER_URL: ${{ secrets.HF_TRAINING_TRIGGER_URL }}
          HF_TRAINING_TRIGGER_METHOD: ${{ secrets.HF_TRAINING_TRIGGER_METHOD }}
          HF_TRAINING_TRIGGER_PAYLOAD: ${{ secrets.HF_TRAINING_TRIGGER_PAYLOAD }}
          HF_TRAINING_TRIGGER_TIMEOUT: ${{ secrets.HF_TRAINING_TRIGGER_TIMEOUT }}
        run: |
          python -m automation.pipeline

      - name: Upload run artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: peallm-data-run
          path: automation_artifacts
